### ISSUE TITLE
how do I use this project :/

### ISSUE THREAD

**Issue by aslansq** [auxoncorp/trace-recorder-parser#13]
Hello

First of thanks for putting this out there. I want to use in my project.
But I do not know anything about rust. Could you write some cmake,make... so I can build?
please prerequisites for environment also

if you are interested
https://github.com/aslansq/freertos_qemu_vscode/tree/main

edit:
I want to convert binary to json for visualization 
https://ui.perfetto.dev/
https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview?tab=t.0#heading=h.yr4qxyxotyw

**Comment by jonlamb-gh** [comment]
Hi @aslansq,

I recommend reading Rust's [Getting started](https://www.rust-lang.org/learn/get-started) page to get familiar with the tools. This library should build on all supported Rust targets and host environments, let me know if you run into build issues. The [CI workflow file](https://github.com/auxoncorp/trace-recorder-parser/blob/master/.github/workflows/ci.yml) has several `cargo` examples that may be useful as well.

You should be able to get JSON from these types by implemented serde's Serialize trait and using something like `serde_json`. Feel free to open a PR.

**Comment by jonlamb-gh** [comment]
FWIW: here's a tool I wrote that uses this library to print the trace data, you could modify it to suite your needs:
https://github.com/jonlamb-gh/trace-recorder-printer

**Comment by aslansq** [comment]
Hmm I guess you give me some reason to play with Rust :)
Aha I did not even know, Rust people have different build system(cargo)
I think @jonlamb-gh project could be enough for me. Thx
